# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import os

class TestPruebalogincorrecta():
  def setup_method(self, method):
    chrome_options = webdriver.ChromeOptions()
    chrome_options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--no-sandbox")
    self.driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"), chrome_options=chrome_options)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_pruebalogincorrecta(self):
    # Test name: prueba login correcta
    # Step # | name | target | value
    # 1 | open | / |
    self.driver.get("https://servidorhombremuerto.herokuapp.com/")
    # 2 | setWindowSize | 1936x1056 |
    self.driver.set_window_size(1936, 1056)
    # 3 | click | id=nombreAdmin |
    self.driver.find_element(By.ID, "nombreAdmin").click()
    # 4 | type | id=nombreAdmin | admin
    self.driver.find_element(By.ID, "nombreAdmin").send_keys("admin")
    # 5 | type | id=passwordAdmin | admin
    self.driver.find_element(By.ID, "passwordAdmin").send_keys("admin")
    # 6 | click | css=.btn |
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    # 7 | assertText | css=html | Cerrar sesión\nBuscar turnos de un maquinista\nCrear maquinista\nQuitar maquinista\nCrear turno\nQuitar turno\nGestión de turnos
    assert self.driver.find_element(By.CSS_SELECTOR, "html").text == "Cerrar sesión\\\\nBuscar turnos de un maquinista\\\\nCrear maquinista\\\\nQuitar maquinista\\\\nCrear turno\\\\nQuitar turno\\\\nGestión de turnos"
